ui_texts = {
    "Russian": {
        "success": "Готово! Вот что от Вас хотят:",
        "sender": "Отправитель",
        "deadline": "Дедлайн",
        "no_deadline": "Сроки не указаны!",
        "nutshell": "📌 Коротко о главном:",
        "translation": "📑 Перевод и объяснение:",
        "consequences": "⚠️ Что будет, если проигнорировать:",
        "spinner": "Нейросеть анализирует письмо...",
        "error_empty": "Пожалуйста, вставьте текст или загрузите файл!",
        "input_mode": "Как вы хотите передать письмо?",
        "mode_text": "Вставить текст вручную",
        "mode_file": "Загрузить файл (PDF, TXT)",
        "paste_text": "Вставьте текст письма на немецком языке (Amtsdeutsch):",
        'letter': 'Расшифруйте письмо 📩',
        "description": "Как легко разобраться в официальных письмах на немецком языке"
    },
    "Ukrainian": {
        "success": "Готово! Ось чого від Вас хочуть:",
        "sender": "Відправник",
        "deadline": "Дедлайн",
        "no_deadline": "Термінів немає!",
        "nutshell": "📌 Коротко про головне:",
        "translation": "📑 Переклад та пояснення:",
        "consequences": "⚠️ Що буде, якщо проігнорувати:",
        "spinner": "Нейромережа аналізує лист...",
        "error_empty": "Будь ласка, вставте текст або завантажте файл!",
        "input_mode": "Як ви хочете передати лист?",
        "mode_text": "Вставити текст вручну",
        "mode_file": "Завантажити файл (PDF, TXT)",
        "paste_text": "Вставте текст листа німецькою мовою (Amtsdeutsch):",
        'letter': 'Розшифруйте лист 📩',
        "description": "Як легко розшифрувати офіційні німецькі листи"
    },
    "English": {
        "success": "All done! Here is what they want from you:",
        "sender": "Sender",
        "deadline": "Deadline",
        "no_deadline": "No deadline!",
        "nutshell": "📌 In a nutshell:",
        "translation": "📑 Translation and explanation:",
        "consequences": "⚠️ What will happen if you ignore this:",
        "spinner": "A neural network analyzes a letter...",
        "error_empty": "Please paste the text or upload a file!",
        "input_mode": "How would you like to provide the letter?",
        "mode_text": "Paste text manually",
        "mode_file": "Upload a file (PDF, TXT)",
        "paste_text": "Paste the text of the German letter (Amtsdeutsch):",
        'letter': 'Decipher the letter 📩',
        "description": "Decoding official German letters the easy way"

    },
    "Simple German (Leichte Sprache)": {
        "success": "Fertig! Das wollen sie von Ihnen:",
        "sender": "Absender",
        "deadline": "Frist",
        "no_deadline": "Keine Frist!",
        "nutshell": "📌 In Kürze:",
        "translation": "📑 Übersetzung und Erklärung:",
        "consequences": "⚠️ Was passiert, wenn Sie das ignorieren:",
        "spinner": "Es wird analysiert...",
        "error_empty": "Bitte fügen Sie Text ein oder laden Sie eine Datei hoch!",
        "input_mode": "Wie möchten Sie den Brief übergeben?",
        "mode_text": "Text manuell eingeben",
        "mode_file": "Datei hochladen (PDF, TXT)",
        "paste_text": "Fügen Sie den Text des deutschen Schreibens (Amtsdeutsch) ein:",
        'letter': 'Entschlüssele den Brief 📩',
        "description": "Deutsche Behördenbriefe ganz einfach entschlüsseln"

    },
}
